apiVersion: v1
kind: Pod
metadata:
  name: api-imagens-pod
  labels:
    app: app-deployment
spec:
  containers:
  - name: api-imagens-container
    image: luizfelipekraus/api-imagens-image
    ports:
    - containerPort: 8004